name: Java CI

on:
  pull_request:
    branches:
      - next
  push:
    branches:
      - next

jobs:

  verify:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 14

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
      - name: Package
        run: mvn --no-transfer-progress -DskipTests=true -Dgpg.skip verify

  test:

    needs: verify

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 14
        docker-img:
          - docker.io/arangodb/arangodb:3.4.9
          - docker.io/arangodb/enterprise:3.4.9
          - docker.io/arangodb/arangodb:3.5.4
          - docker.io/arangodb/enterprise:3.5.4
          - docker.io/arangodb/arangodb:3.6.2
          - docker.io/arangodb/enterprise:3.6.2
          - docker.io/arangodb/arangodb-preview:3.7.0-alpha.2
          - docker.io/arangodb/enterprise-preview:3.7.0-alpha.2

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
      - name: Info
        run: mvn -version
      - name: Configure reuse containers
        run: echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties
      - name: Test
        run: mvn -e --no-transfer-progress test -DexcludedGroups="resiliency" -Dtest.docker.image="${{matrix.docker-img}}" -Darango.license.key="$ARANGO_LICENSE_KEY" -Dtestcontainers.reuse.enable=true
        env:
          ARANGO_LICENSE_KEY: ${{secrets.ARANGO_LICENSE_KEY}}

  sonar:

    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Info
        run: mvn -version
      - name: Analyze
        run: mvn -e --no-transfer-progress clean verify sonar:sonar -Dgpg.skip -Dtest.docker.image="docker.io/arangodb/enterprise:3.6.2" -Darango.license.key="$ARANGO_LICENSE_KEY"
        env:
          ARANGO_LICENSE_KEY: ${{secrets.ARANGO_LICENSE_KEY}}
          SONAR_LOGIN: ${{secrets.SONAR_LOGIN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
